### ISSUE TITLE
Plan output missing from PR comment (and workflow output)

### ISSUE THREAD

**Issue by paambaati** [hashicorp/terraform-cdk-action#12]
This is the workflow configuration –

```yaml
- name: generate terraform plan
  uses: hashicorp/terraform-cdk-action@v0.1.0
  with:
    terraformVersion: 1.2.9
    cdktfVersion: 0.12.2
    stackName: stg
    mode: plan-only
    terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
    githubToken: ${{ secrets.GITHUB_TOKEN }}
    workingDirectory: infra
    commentOnPr: true
```

The output when the workflow is run –

```
stg  Creating Terraform Cloud configuration version

stg  Creating Terraform Cloud configuration version
stg  Created Terraform Cloud configuration version cv-redacted

stg  Created Terraform Cloud configuration version cv-redacted
stg  Zipping up the directory cdktf.out/stacks/stg

stg  Zipping up the directory cdktf.out/stacks/stg
stg  Uploading the directory to Terraform Cloud

stg  Uploading the directory to Terraform Cloud
stg  Uploaded the directory to Terraform Cloud

stg  Uploaded the directory to Terraform Cloud
stg  Waiting for configuration version to become ready...

stg  Waiting for configuration version to become ready...
stg  Creating speculative Terraform Cloud run

stg  Creating speculative Terraform Cloud run
stg  Created speculative Terraform Cloud run: https://app.terraform.io/app/redacted/workspaces/stg/runs/run-redacted

stg  Created speculative Terraform Cloud run: https://app.terraform.io/app/redacted/workspaces/stg/runs/run-redacted
stg  Speculative Terraform Cloud run done

stg  Speculative Terraform Cloud run done
stg  Getting plan output

stg  Getting plan output
```

You can see the workflow stops at `Getting plan output`, although it doesn't exit with an error code.

![Screengrab 2022-10-18 at 16 44 33@2x](https://user-images.githubusercontent.com/5381764/196414872-cde7eee8-05fa-4ddd-a530-c61defbd79d7.png)

Finally, the PR comment looks like this –

![Screengrab 2022-10-18 at 16 45 31@2x](https://user-images.githubusercontent.com/5381764/196415004-e75d9d61-471b-417d-9c7e-b85197eec547.png)

I can confirm that the plan succeeded on the Terraform Cloud web UI, and the plan in fact shows 2 changes. However, this doesn't show up in the workflow output.
