### ISSUE TITLE
Required token could not be found

### ISSUE THREAD

**Issue by thekiwi** [hashicorp/terraform-cdk-action#16]
Hi! I'm trying to use this GitHub action to run a `plan` on my project.

Here's my configuration:
```
      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.5
        with:
          terraformVersion: 1.3.5
          cdktfVersion: 0.14.1
          workingDirectory: ./platform/
          stackName: platform
          mode: plan-only
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

I've configured the `TF_API_TOKEN` as a GitHub Action Secret within the repository. 

Yet, the action runs, it fails with the following:

```
(node:1797) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/usr/bin/unzip -o -q /home/runner/work/_temp/39070cfa-bde4-4aa2-a743-25eacf08c2eb
/opt/hostedtoolcache/node/16.18.0/x64/bin/npm install -g cdktf-cli@0.14.1

added 294 packages, and audited 349 packages in 5s

28 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/opt/hostedtoolcache/node/16.18.0/x64/bin/cdktf plan platform
platform  Initializing Terraform Cloud...

platform  Initializing Terraform Cloud...
Error: 022-11-22T16:50:09.521] [ERROR] default - 
Error: Required token could not be found

Run the following command to generate a token for app.terraform.io:
    terraform login



Error: 022-11-22T16:50:09.521] [ERROR] default - 
Error: Required token could not be found

Run the following command to generate a token for app.terraform.io:
    terraform login


platform  Error: Required token could not be found

          Run the following command to generate a token for app.terraform.io:
              terraform login

platform  Error: Required token could not be found

          Run the following command to generate a token for app.terraform.io:
              terraform login

⠙  Processing


⠙  Processing
Warning: External Error: Stack failed to plan: platform. Please check the logs for more information.

External Error: Stack failed to plan: platform. Please check the logs for more information.
Error: The process '/opt/hostedtoolcache/node/16.18.0/x64/bin/cdktf' failed with exit code 1
```

When enabling the Action debug logs, GitHub definitely loads the variable in, and when using the same token locally as an environment variable for `cdktf-cli` (using the env var `TERRAFORM_CLOUD_TOKEN`) it works fine. 

Any ideas why the action can't see the token, or where I could look to figure out what's going wrong?

**Comment by NotErickG** [comment]
I had to hack it and do something like this as a preceding step.

```    - name: Install dependencies
      run: |
        mkdir -p ~/.terraform.d
        cat <<EOT >> ~/.terraform.d/credentials.tfrc.json
        {
          "credentials": {
            "app.terraform.io": {
              "token": "$TFE_TOKEN"
            }
          }
        }
        EOT
      env:
        TFE_TOKEN: ${{secrets.TFE_TOKEN}}```

**Comment by sbkg0002** [comment]
I have this issue since cdktf v0.15.0. Even the workaround by @NotErickG doesn't work.

**Comment by sbkg0002** [comment]
Is there any update on this?

**Comment by leamarty** [comment]
It seems that the CLI searches for a specific environment variable depending on the "hostname" you are trying to reach.
For example, if you are configuring your backend to connect to `app.terraform.io`, then the CLI will try to use the `TF_TOKEN_app_terraform_io` env var (if available).

This solved things for me:

```yml
      - name: Run Terraform CDK Plan
        uses: hashicorp/terraform-cdk-action@v0.1.0
        with:
          terraformVersion: 1.3.0
          cdktfVersion: 0.15.5
          stackName: your-stack
          mode: plan-only
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }} # Useless
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
```
