### ISSUE TITLE
Add comments to the commit instead of to a PR

### ISSUE THREAD

**Issue by jdraymon** [hashicorp/terraform-cdk-action#216]
### Description

Typically, terraform `apply` jobs to an environment will not occur as a result of a PR, but rather after merging to the main branch. It is still desirable to have a durable record of the results of plan/apply, however, so it would be helpful to have an option to direct the comment to a specific commit instead of to the PR.

Proposed input change:
Change `commentOnPr` from a `boolean` to a `string` input:
```yaml
  commentMode:
    description: Where to comment the results of the operation; on the `commit`, the `pr`, or `none` of the above
    default: pr
    required: false
```

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment
