### ISSUE TITLE
How to debug Secondary Rate Issues?

### ISSUE THREAD

**Issue by levelupatlas-mat** [hashicorp/terraform-cdk-action#224]
### Description

One of my GHA keeps randomly hitting some secondary rate issue, but debugging it has been giving me a headache. How is one expected to debug and resolve those? My IaC only contains 1 stack. It's really annoying since this step is the one that takes 90% of the GHA's run time, but it fails like that every 3-4 runs inconsistently.

### GitHub Action Version

v5

### Configuration

cdktfVersion: 0.20.9
terraformVersion: 1.9.7
stackName: ${{ env.STACK_NAME }}
mode: auto-approve-apply
terraformCloudToken: ${{ env.TF_API_TOKEN }}
githubToken: ${{ secrets.GITHUB_TOKEN }}

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rockcheung2004** [comment]
I have the same issue. 

- The github secondary rate limit error was shown for me more than half the time at the end of a `synth-only` step or at the end of a `auto-approve-apply` step. 
- The terraform apply would actually have succeeded, but the step will ultimately fail at the very end. 
- Adding `cdktfArgs: "--terraform-parallelism=1"` did not help much.

```
- name: Synth TF
        uses: hashicorp/terraform-cdk-action@49ec8ab82c05c589eea8461fd4c07634aa749e41 #v4.0.1
        with:
          cdktfVersion: 0.20.7
          terraformVersion: 1.8.1
          workingDirectory: backend
          mode: synth-only
          githubToken: ${{ secrets.GITHUB_TOKEN }}
- name: Plan and Apply TF
        uses: hashicorp/terraform-cdk-action@49ec8ab82c05c589eea8461fd4c07634aa749e41 #v4.0.1
        with:
          cdktfVersion: 0.20.7
          terraformVersion: 1.8.1
          workingDirectory: backend
          mode: auto-approve-apply
          stackName: p2
          cdktfArgs: "--terraform-parallelism=1"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```
