### ISSUE TITLE
Duplicated STDOUT

### ISSUE THREAD

**Issue by araks-hypixelstudios** [hashicorp/terraform-cdk-action#39]
The github action generates duplicated stdout for all the logs that are created by the action, both from NPM and CDKTF.

NPM Log Example:

```
Warning: #######################################################################################################
### You are currently using jsii@1.x. We recommend upgrading to jsii@5.0.x or later. This will      ###
### allow you to use modern TypeScript syntax, and improves compatibility with many common          ###
### dependencies. For example, recent versions of @types/node.                                      ###
###                                                                                                 ###
### 5.0.x and subsequent releases of jsii use the same major.minor version as the TypeScript        ###
### compiler they are built on. We recommend declaring a minor-pinned (also known as "tilde")       ###
### dependency on jsii (e.g: `"jsii": "5.0.x"` or `"jsii": "~5.0.7"`).                              ###
###                                                                                                 ###
### For more information, see: https://aws.github.io/jsii/compiler-and-rosetta-maintenance/         ###
###                                                                                                 ###
### This warning can be suppressed by setting the JSII_SUPPRESS_UPGRADE_PROMPT environment variable ###
#######################################################################################################

#######################################################################################################
### You are currently using jsii@1.x. We recommend upgrading to jsii@5.0.x or later. This will      ###
### allow you to use modern TypeScript syntax, and improves compatibility with many common          ###
### dependencies. For example, recent versions of @types/node.                                      ###
###                                                                                                 ###
### 5.0.x and subsequent releases of jsii use the same major.minor version as the TypeScript        ###
### compiler they are built on. We recommend declaring a minor-pinned (also known as "tilde")       ###
### dependency on jsii (e.g: `"jsii": "5.0.x"` or `"jsii": "~5.0.7"`).                              ###
###                                                                                                 ###
### For more information, see: https://aws.github.io/jsii/compiler-and-rosetta-maintenance/         ###
###                                                                                                 ###
### This warning can be suppressed by setting the JSII_SUPPRESS_UPGRADE_PROMPT environment variable ###
#######################################################################################################
```

CDKTF CLI Log Example:

```
stack1 Successfully configured the backend "s3"! Terraform will automatically
         use this backend unless the backend configuration changes.

stack1 Successfully configured the backend "s3"! Terraform will automatically
         use this backend unless the backend configuration changes.
stack 2 Successfully configured the backend "s3"! Terraform will automatically
                 use this backend unless the backend configuration changes.

stack2 Successfully configured the backend "s3"! Terraform will automatically
                 use this backend unless the backend configuration changes.
stack3 Successfully configured the backend "s3"! Terraform will automatically
                use this backend unless the backend configuration changes.

stack3 Successfully configured the backend "s3"! Terraform will automatically
                use this backend unless the backend configuration changes.
```

Workflow example

```yaml
name: "CDKTF Deploy"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "CDKTF Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout source code
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.16
        with:
          terraformVersion: 1.3.7
          cdktfVersion: 0.15.5
          workingDirectory: cdktf
          stackName: "*"
          mode: auto-approve-apply
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          commentOnPr: false
        env:
          # Disable logs related to NPM installation
          npm_config_loglevel: silent
          NODE_NO_WARNINGS: 1
```

The issue also happens if I add `setup-node` step to force Node 16, as well action's `v0.1.0` version like the workflow examples in the documentation.
