### ISSUE TITLE
Authentication Error: Error in getting Token from Azure using service principal

### ISSUE THREAD

**Issue by ankitatdnv** [hashicorp/terraform-cdk-action#66]
### Description

I am trying to migrate to CDKTF and it's working fine while running locally, but it's failing with following error when run in github actions:
```
Error: building account: could not acquire access token to parse claims: clientC
            redentialsToken: received HTTP status 400 with response: ***"error":"invalid_reque
            st","error_description":"AADSTS900023: Specified tenant identifier *** is neither a valid DNS name, nor a valid external domai
            n.\r\nTrace ID: ee37609e-fc29-4507-b71b-cbfa40fe1c00\r\nCorrelation ID: 67c34b1d
            -9a13-425b-817e-fa7ddab8e12d\r\nTimestamp: 2023-07-26 11:38:37Z","error_codes":[
            900023],"timestamp":"2023-07-26 11:38:37Z","trace_id":"ee37609e-fc29-4507-b71b-c
            bfa40fe1c00","correlation_id":"67c34b1d-9a13-425b-817e-fa7ddab8e12d","error_uri"

```

Please find below my workflow steps:

```
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
           
           

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '16.20.1'        
        registry-url: 'https://registry.npmjs.org' 
        
    - name: Install NPM Packages
      run: npm install
      working-directory: ${{ env.working-directory }}
    
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Get TF CDK CLI          
      run: npx cdktf-cli get     
      working-directory: ${{ env.working-directory }}


    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Run TF CDK
      uses: hashicorp/terraform-cdk-action@v0.1.31 
      env: 
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      with:        
        terraformVersion: ${{ env.TERRAFORM_VERSION }}
        cdktfVersion: ${{ env.CDKTF_VERSION }}
        mode: auto-approve-apply
        workingDirectory: ${{ env.working-directory }} 
        stackName: "mytest-app"
        githubToken: ${{ secrets.PAT_GITHUB }}

```

### GitHub Action Version

v0.1.31

### Configuration

        terraformVersion: ${{ env.TERRAFORM_VERSION }}
        cdktfVersion: ${{ env.CDKTF_VERSION }}
        mode: auto-approve-apply
        workingDirectory: ${{ env.working-directory }} 
        stackName: "mytest-app"
        githubToken: ${{ secrets.PAT_GITHUB }}

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment
